# to run it run "sudo ansible-pull -U https://github.com/arthurnunesc/ansible.git"
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update_repositories
      dnf:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
