- name: Install packages
  package:
    name:
      - htop
      - mc
      - tmux
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - python-psutil
    state: present
